app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://polar-postgres:5432/polardb_catalog
      username: postgres
      password: postgres
      pool-size: 10

spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://polar-postgres:5432/polardb_catalog?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    show-sql: true