app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/store
      username: postgres
      password: postgres
      pool-size: 10

spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  jpa:
    show-sql: true